steps:
  setup:
    image: maven:3.8.6-openjdk-17
    commands:
      - echo "Setting up environment"
      - mvn clean install -DskipTests

  test:
    image: maven:3.8.6-openjdk-17
    commands:
      - echo "Running unit tests"
      - mvn test